### ISSUE TITLE
Missing descriptions in full schemas

### ISSUE THREAD

**Issue by skoehnen** [HumanBrainProject/openMINDS#14]
Lyuba and I saw that the description from the vocab are not represented in the generated schemas.
Did we do something wrong or is this not yet implemented.

**Comment by lzehl** [comment]
@skoehnen the PR #13 covers for the first time the general descriptions for the properties. 

Providing a general description for the schema types is not yet done, but already on my list. 

Independent of this, was the integration of the descriptions not in the full schemas yet because of the distributed generation we had before. I discussed this with @olinux. This was one of the reasons why we now thought to centralize everything on openMINDS (considering the generation of the schemas). 

@olinux was this covered with the latest update in the generator already or does this have to be implemented later? (It's working for the HTMLs as far as I know so I thought it's in already)

**Comment by skoehnen** [comment]
@lzehl should we close this issue?

**Comment by lzehl** [comment]
Yes. It's solved now. The latest target files should now include descriptions for all properties. There might still be some missing descriptions for the types but we can add them and optimize the existing ones step wise.
